export default {
    COMPLETE_ITEM: 'COMPLETE_ITEM',
    SELECT_FOOTER_BTN: 'SELECT_FOOTER_BTN',
    DELETE_ITEM: 'DELETE_ITEM',
    ADD_ITEM: 'ADD_ITEM',
    UPDATE_ALL: 'UPDATE_ALL',
    UPDATE_ITEM: 'UPDATE_ITEM'
}